[package]
name = "ontoenv-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
regex = "1.10.3"
sophia = { version = "0.8.0", features = ["xml"] }
walkdir = "2.4.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
json-ld = "0.15.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sophia_jsonld = "0.8.0"
env_logger = "0.11.1"
log = "0.4.20"
serde_regex = "1.1.0"
glob-match = "0.2.1"
chrono = "0.4.33"

