name: Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: ${{ matrix.os }} build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-14
          - windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install Python
        run: uv python install

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libssl-dev

      - name: Clean build cache
        run: cargo clean
        shell: bash

      - name: Build Rust workspace
        run: cargo build --workspace --release

      - name: Test Rust workspace
        run: cargo test --workspace --release

      - name: Build Python package
        working-directory: python
        run: uv run maturin build --release --features abi3
        
      - name: Install Python package
        working-directory: python
        run: uv pip install --no-index --find-links=../target/wheels/ pyontoenv
        
      - name: Test Python package
        working-directory: python
        run: uv run python -m unittest discover -s tests
